# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [6]:
data = pd.read_csv("Churn_Modelling.csv")
X = data.iloc[: ,3:-1].values
Y = data.iloc[:, -1].values


In [9]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [10]:
print(Y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [13]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X, Y, test_size =  0.2 , random_state = 0)

### Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()


### Adding the first layer or input layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6 , activation = 'relu'))

### Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6 , activation = 'relu'))

### Adding the output layer

In [23]:
ann.add(tf.keras.layers.Dense(units=1 , activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [25]:
ann.fit(X_train,Y_train,batch_size = 32 , epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6465 - accuracy: 0.6750
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4743 - accuracy: 0.8059
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4280 - accuracy: 0.8176
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4105 - accuracy: 0.8274
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3973 - accuracy: 0.8357
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3848 - accuracy: 0.8409
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3735 - accuracy: 0.8446
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3643 - accuracy: 0.8501
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3584 - accuracy: 0.8519
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3540 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [28]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,5000]]))>0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [30]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)